# Generated by Django 3.2 on 2022-11-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=60, null=True)),
                ('location', models.CharField(max_length=60, null=True)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
