# Generated by Django 3.2 on 2022-11-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Body',
        ),
        migrations.AddField(
            model_name='contact',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
