# Generated by Django 3.2 on 2022-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
