# Generated by Django 3.2 on 2022-11-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categories_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='friendly_name',
        ),
    ]
